#
# Sorry for my eng, it's not my primary language, I'm from the Belarus ;)
# Report an issue: https://github.com/eereeska/prettier/issues
# Commands & Permissions: https://github.com/eereeska/prettier/wiki/Commands-&-Permissions
#

# There you can totally enable/disable some parts of Prettier
modules:
  betterItemFrames:
    enable: true
    visibility:
      allowEmptyFrames: false
    fixation:
      allowEmptyFrames: false

# Format prefix must be unique
# Range - range value in blocks. Use '-1' for sender-world-broadcast & '-2' for truly-global-broadcast
# Placeholders supported: PlaceholderAPI & by default: @world, @player_name, @player_display_name, @message
chat-format:
  enabled: true
  formats:
    local:
      range: 50
      prefix: ""
      format: "§8[§7L§8] §f@player_display_name §8» §7@message"
    global:
      range: -1
      prefix: "!"
      format: "§8[§bG§8] §f@player_display_name §8» §7@message"
    vip:
      range: 100
      prefix: "!v"
      format: "§8[§6V§8] §f@player_display_name §8» §7@message"
      # these options are optional (you can remove them or use in other formats)
      send-permission: "prettier.chat.format.send.vip"
      send-no-permission: "$AB: §cYou don't have permission to write in the §6VIP §cchat!"
      receive-permission: "prettier.chat.format.receive.vip"

# Commands that will totally blocked / removed from the server (but still available from console)
disabled-commands:
  - op
  - deop
  - pl

# Tab-complete commands whitelist
# Players wont be able to see the command without permission, but still able to execute them
# So you can just give to players visible-if-has-permission commands list
allowed-commands:
  default:
    - about
  moderator:
    - ban
    - kick
    - mute
    - warn
  admin:
    - ban-ip