#
# Sorry for my eng, it's not my primary language, I'm from Belarus ;)
# You can report an issue right here: https://github.com/eereeska/prettier/issues
#
# I would be very grateful for the donation <3
# Current goal: Own minecraft account
# https://www.paypal.me/eereeska
#

#
# Please, use '§' symbol for color selection instead of '&'
# This is the right way to use colors in Minecraft
#

#
# You can use $CHAT: or $AB(ACTIONBAR): to choose where you want to display the message where the Prettier sends any message
# Example: "$CHAT: §cSimple chat message" or "$AB: §cSimple action bar message"
# Or, you can use 'none' to disable sending the message
#

commands:
  prettier:
    permission: "prettier.commands.prettier" #permission to use that command
    no-permission-message: "$CHAT: §8[§5Prettier§8] §cYou don't have permission to use this command" #use 'none' to disable this message"

permissions:
  group: "prettier.commands.allowed.{group}"
  bypass: "prettier.commands.allowed.bypass"

# All possible messages outgoing from Prettier
messages:
  config-reload-success: "§aConfiguration was successfully reloaded"

# Join & Quit message customization
# Use 'disable' to disable message editing by Prettier or 'hide' to completely hide the message
# Placeholders supported: PlaceholderAPI & by default: @world, @player_name, @player_display_name
player-join-message: "§8[§a+§8] §8[§7%vault_prefix%§8] §f%player_name%"
player-quit-message: "§8[§c-§8] §8[§7%vault_prefix%§8] §f%player_name%"

# Format prefix must be unique
# Range - range value in blocks. Use '-1' for sender-world-broadcast & '-2' for truly-global-broadcast
# Placeholders supported: PlaceholderAPI & by default: @world, @player_name, @player_display_name, @message
chat-format:
  enabled: true
  formats:
    local:
      range: 50
      prefix: ""
      format: "§8[§7L§8] §f@player_display_name §8» §7@message"
    global:
      range: -1
      prefix: "!"
      format: "§8[§bG§8] §f@player_display_name §8» §7@message"
    vip:
      range: 100
      prefix: "!v"
      format: "§8[§6V§8] §f@player_display_name §8» §7@message"
      # these options are optional (you can remove them or use in other formats)
      send-permission: "prettier.chat.format.send.vip"
      send-no-permission: "$AB: §cYou don't have permission to write in the §6VIP §cchat!"
      receive-permission: "prettier.chat.format.receive.vip"

# Commands that will totally blocked / removed from the server (but still available from console)
disabled-commands:
  - op
  - deop
  - pl

# Tab-complete commands whitelist
# Players wont be able to see the command without permission, but still able to execute them
# So you can just give to players visible-if-has-permission commands list
allowed-commands:
  default:
    - about
  moderator:
    - ban
    - kick
    - mute
    - warn
  admin:
    - ban-ip